/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avroschema.linked;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SpatialWordLinked extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SpatialWordLinked\",\"namespace\":\"avroschema.linked\",\"fields\":[{\"name\":\"modified_word\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"space\",\"type\":{\"type\":\"record\",\"name\":\"SpaceLinked\",\"fields\":[{\"name\":\"core_words\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TokenLinked\",\"fields\":[{\"name\":\"pos\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"ner\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"span\",\"type\":{\"type\":\"record\",\"name\":\"Span\",\"fields\":[{\"name\":\"start_index\",\"type\":[\"int\",\"null\"]},{\"name\":\"end_index\",\"type\":[\"int\",\"null\"]}]}},{\"name\":\"lemma\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"word\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"index\",\"type\":[\"int\",\"null\"]},{\"name\":\"w_link\",\"type\":{\"type\":\"record\",\"name\":\"WikiLink\",\"fields\":[{\"name\":\"offset_begin_ind\",\"type\":\"int\"},{\"name\":\"offset_end_ind\",\"type\":\"int\"},{\"name\":\"phrase\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"wiki_link\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}]}}]},{\"name\":\"pre_mods\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"TokenLinked\"}]},{\"name\":\"post_mods\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"TokenLinked\"}]},{\"name\":\"all_words\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"TokenLinked\"}]},{\"name\":\"predicate\",\"type\":[\"null\",\"TokenLinked\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String modified_word;
  @Deprecated public avroschema.linked.SpaceLinked space;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SpatialWordLinked() {}

  /**
   * All-args constructor.
   */
  public SpatialWordLinked(java.lang.String modified_word, avroschema.linked.SpaceLinked space) {
    this.modified_word = modified_word;
    this.space = space;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return modified_word;
    case 1: return space;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: modified_word = (java.lang.String)value$; break;
    case 1: space = (avroschema.linked.SpaceLinked)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'modified_word' field.
   */
  public java.lang.String getModifiedWord() {
    return modified_word;
  }

  /**
   * Sets the value of the 'modified_word' field.
   * @param value the value to set.
   */
  public void setModifiedWord(java.lang.String value) {
    this.modified_word = value;
  }

  /**
   * Gets the value of the 'space' field.
   */
  public avroschema.linked.SpaceLinked getSpace() {
    return space;
  }

  /**
   * Sets the value of the 'space' field.
   * @param value the value to set.
   */
  public void setSpace(avroschema.linked.SpaceLinked value) {
    this.space = value;
  }

  /** Creates a new SpatialWordLinked RecordBuilder */
  public static avroschema.linked.SpatialWordLinked.Builder newBuilder() {
    return new avroschema.linked.SpatialWordLinked.Builder();
  }
  
  /** Creates a new SpatialWordLinked RecordBuilder by copying an existing Builder */
  public static avroschema.linked.SpatialWordLinked.Builder newBuilder(avroschema.linked.SpatialWordLinked.Builder other) {
    return new avroschema.linked.SpatialWordLinked.Builder(other);
  }
  
  /** Creates a new SpatialWordLinked RecordBuilder by copying an existing SpatialWordLinked instance */
  public static avroschema.linked.SpatialWordLinked.Builder newBuilder(avroschema.linked.SpatialWordLinked other) {
    return new avroschema.linked.SpatialWordLinked.Builder(other);
  }
  
  /**
   * RecordBuilder for SpatialWordLinked instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SpatialWordLinked>
    implements org.apache.avro.data.RecordBuilder<SpatialWordLinked> {

    private java.lang.String modified_word;
    private avroschema.linked.SpaceLinked space;

    /** Creates a new Builder */
    private Builder() {
      super(avroschema.linked.SpatialWordLinked.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avroschema.linked.SpatialWordLinked.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.modified_word)) {
        this.modified_word = data().deepCopy(fields()[0].schema(), other.modified_word);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.space)) {
        this.space = data().deepCopy(fields()[1].schema(), other.space);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SpatialWordLinked instance */
    private Builder(avroschema.linked.SpatialWordLinked other) {
            super(avroschema.linked.SpatialWordLinked.SCHEMA$);
      if (isValidValue(fields()[0], other.modified_word)) {
        this.modified_word = data().deepCopy(fields()[0].schema(), other.modified_word);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.space)) {
        this.space = data().deepCopy(fields()[1].schema(), other.space);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'modified_word' field */
    public java.lang.String getModifiedWord() {
      return modified_word;
    }
    
    /** Sets the value of the 'modified_word' field */
    public avroschema.linked.SpatialWordLinked.Builder setModifiedWord(java.lang.String value) {
      validate(fields()[0], value);
      this.modified_word = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'modified_word' field has been set */
    public boolean hasModifiedWord() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'modified_word' field */
    public avroschema.linked.SpatialWordLinked.Builder clearModifiedWord() {
      modified_word = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'space' field */
    public avroschema.linked.SpaceLinked getSpace() {
      return space;
    }
    
    /** Sets the value of the 'space' field */
    public avroschema.linked.SpatialWordLinked.Builder setSpace(avroschema.linked.SpaceLinked value) {
      validate(fields()[1], value);
      this.space = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'space' field has been set */
    public boolean hasSpace() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'space' field */
    public avroschema.linked.SpatialWordLinked.Builder clearSpace() {
      space = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public SpatialWordLinked build() {
      try {
        SpatialWordLinked record = new SpatialWordLinked();
        record.modified_word = fieldSetFlags()[0] ? this.modified_word : (java.lang.String) defaultValue(fields()[0]);
        record.space = fieldSetFlags()[1] ? this.space : (avroschema.linked.SpaceLinked) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
